config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("", include("core.urls", namespace="core")),
    path("rooms/", include("rooms.urls", namespace="rooms")),
    path("users/", include("users.urls", namespace="users")),
    path("reservations/", include("reservations.urls", namespace="reservations")),
    path("reviews/", include("reviews.urls", namespace="reviews")),
    path("lists/", include("lists.urls", namespace="lists")),
    path("conversations/", include("conversations.urls", namespace="conversations")),
    path("admin/", admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/urls.py
from django.urls import path
from rooms import views as room_views

app_name = "core"

urlpatterns = [
    path("", room_views.HomeView.as_view(), name="home"),
]

lists/urls.py
from django.urls import path
from . import views

app_name = "lists"

urlpatterns = [
    path("toggle/<int:room_pk>/", views.toggle_view, name="toggle"),
    path("favs/", views.FavListView.as_view(), name="favs"),
]

rooms/urls.py
from django.urls import path
from . import views

app_name = "rooms"

urlpatterns = [
    path("<int:pk>/", views.RoomDetailView.as_view(), name="detail"),
    path("search/", views.SearchView.as_view(), name="search"),
    path("create/", views.CreateRoomView.as_view(), name="create"),
    path("<int:pk>/edit/", views.EditRoomView.as_view(), name="edit"),
    path("<int:pk>/photos/", views.RoomPhotosView.as_view(), name="photos"),
    path("<int:pk>/photos/add/", views.CreatePhotoView.as_view(), name="add-photo"),
    path(
        "<int:room_pk>/photos/<int:photo_pk>/delete/",
        views.delete_photo,
        name="photo-delete",
    ),
    path(
        "<int:room_pk>/photos/<int:photo_pk>/edit/",
        views.EditPhotoView.as_view(),
        name="photo-edit",
    ),
]

users/urls.py
from django.urls import path
from . import views

app_name = "users"

urlpatterns = [
    path("login/", views.LoginView.as_view(), name="login"),
    path("login/github/", views.github_login, name="github-login"),
    path("login/github/callback/", views.github_callback, name="github-callback"),
    path("login/kakao/", views.kakao_login, name="kakao-login"),
    path("login/kakao/callback/", views.kakao_callback, name="kakao-callback"),
    path("logout/", views.log_out, name="logout"),
    path("signup/", views.SignUpView.as_view(), name="signup"),
    path(
        "verify/<str:key>/", views.complete_verification, name="complete-verification"
    ),
    path("update-profile/", views.UpdateProfileView.as_view(), name="update"),
    path(
        "change-password/", views.PasswordChangeView.as_view(), name="change-password"
    ),
    path("<int:pk>/", views.UserProfileView.as_view(), name="profile"),
    path("switch-hosting/", views.switch_hosting, name="switch-hosting"),
    path("switch-language/", views.switch_lang, name="switch-language"),
]

templates/partials/device-line.html
<div class="flex items-center w-full">
    <div class="w-full h-px bg-gray-400"></div>
    <{{h_level}} class="text-2xl font-bold px-2 whitespace-pre">{{title}}</{{h_level}}>
    <div class="w-full h-px bg-gray-400"></div>
</div>

templates/partials/footer.html
{% load i18n %}
<footer class="container mx-auto text-center mt-12 py-10 border-t text-gray-600 relative">
    <div class="absolute top-0 right-0 w-40 mt-2">
        {% get_current_language as LANGUAGE_CODE %}
        <select id="js-lang" class="p-2">
            <option value="ko" {% if LANGUAGE_CODE == 'ko' %}selected{% endif %}>Korean</option>
            <option value="en" {% if LANGUAGE_CODE == 'en' %}selected{% endif %}>English</option>
        </select>
    </div>
    <p>
        &copy; 2022 Nbnb, Inc. All rights reserved. Please don't copy us.
    </p>
</footer>

templates/partials/messages.html
{% if messages %}
    <ul class="absolute mx-auto left-0 right-0 top-0 flex justify-center max-w-sm">
        {% for message in messages %}
        <li class="message {% if message.tags %}{{message.tags}}"{% endif %}>{{message}}</li>
        {% endfor %}
    </ul>
{% endif %}

templates/partials/nav.html
{% load static i18n %}
  <ul class="flex items-center font-bold h-full">
    {% if user.is_authenticated %}
      <li class="nav_link">
        <a href="{% url 'users:switch-hosting' %}">
        {% if request.session.is_hosting %}
          {% trans "Stop hosting" %}
        {% else %}
          {% trans "Start hosting" %}
        {% endif %}
          
        </a>
      </li>
      {% if request.session.is_hosting %}
      <li class="nav_link"><a href="{% url 'rooms:create' %}">{% trans "Create room" %}</a></li>
      {% endif %}
      <li class="nav_link"><a href="{% url 'lists:favs' %}">{% trans "Favs" %}</a></li>
      <li class="nav_link"><a href="{{user.get_absolute_url}}">{% trans "Profile" %}</a></li>
      <li class="nav_link"><a href="{% url 'users:logout' %}">{% trans "Log out" %}</a></li>
    {% else %}
      <li class="nav_link"><a href="{% url 'users:login' %}">{% trans "Log in" %}</a></li>
      <li class="nav_link"><a href="{% url 'users:signup' %}">{% trans "Sign up" %}</a></li>
    {% endif %}
  </ul>

templates/partials/room_card.html
<div class="w-1/4 mb-8 px-2">
    <a href="{% url 'rooms:detail' room.pk %}">
        <div class="w-full h-60 bg-cover bg-center rounded-lg" style="background-image:url({{room.first_photo}})"></div>
        <div class="flex justify-between my-2">
            <div>
                {% if room.host.is_superhost %}
                <span class="uppercase font-semibold border border-black text-black rounded px-1 py-px mr-1">superhost</span>
                {% endif %}
                <span class="text-gray-500 text-sm font-light truncate ...">{{room.city}} &middot; {{room.country.name}}</span>
            </div>
            <div class="flex items-center">
                <i class="fas fa-star text-pink-600 text-xs mr-1"></i>
                {{room.total_rating}}
            </div>
        </div>
        <div class="text-black truncate ...">{{room.name}}</div>
    </a>
</div>

templates/partials/social_login.html
<div class="flex flex-col w-full">
    <a href="{% url 'users:github-login' %}" class="c-btn-full bg-black border-black text-white">
        <i class="fab fa-github mr-2 fa-lg"></i>Continue with Github
    </a>
    <a href="{% url 'users:kakao-login' %}" class="c-btn-full bg-yellow-300 text-black border-yellow-600">
        <i class="fas fa-comment mr-2 fa-lg"></i>Continue with Kakao
    </a>
</div>

<div class="flex items-center w-full">
    <div class="w-full h-px bg-gray-400"></div>
    <span class="font-bold px-2">or</span>
    <div class="w-full h-px bg-gray-400"></div>
</div>