config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("", include("core.urls", namespace="core")),
    path("rooms/", include("rooms.urls", namespace="rooms")),
    path("users/", include("users.urls", namespace="users")),
    path("reservations/", include("reservations.urls", namespace="reservations")),
    path("reviews/", include("reviews.urls", namespace="reviews")),
    path("lists/", include("lists.urls", namespace="lists")),
    path("conversations/", include("conversations.urls", namespace="conversations")),
    path("admin/", admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/urls.py
from django.urls import path
from rooms import views as room_views

app_name = "core"

urlpatterns = [
    path("", room_views.HomeView.as_view(), name="home"),
]

lists/urls.py
from django.urls import path
from . import views

app_name = "lists"

urlpatterns = [
    path("toggle/<int:room_pk>/", views.toggle_view, name="toggle"),
    path("favs/", views.FavListView.as_view(), name="favs"),
]

rooms/urls.py
from django.urls import path
from . import views

app_name = "rooms"

urlpatterns = [
    path("<int:pk>/", views.RoomDetailView.as_view(), name="detail"),
    path("search/", views.SearchView.as_view(), name="search"),
    path("create/", views.CreateRoomView.as_view(), name="create"),
    path("<int:pk>/edit/", views.EditRoomView.as_view(), name="edit"),
    path("<int:pk>/photos/", views.RoomPhotosView.as_view(), name="photos"),
    path("<int:pk>/photos/add/", views.CreatePhotoView.as_view(), name="add-photo"),
    path(
        "<int:room_pk>/photos/<int:photo_pk>/delete/",
        views.delete_photo,
        name="photo-delete",
    ),
    path(
        "<int:room_pk>/photos/<int:photo_pk>/edit/",
        views.EditPhotoView.as_view(),
        name="photo-edit",
    ),
]

rooms/models.py
from django.db import models
from django.urls import reverse
from django.utils import timezone
from dateutil.relativedelta import relativedelta
from django_countries.fields import CountryField
from core import models as core_models
from cal import Calendar


class AbstractItem(core_models.TimeStampedModel):

    """Abstarct Item"""

    name = models.CharField(max_length=80)

    class Meta:
        abstract = True

    def __str__(self) -> str:
        return self.name


class RoomType(AbstractItem):

    """RoomType Model Definition"""

    class Meta:
        verbose_name = "Room Type"
        ordering = ("name",)


class Amenity(AbstractItem):

    """Amenity Model Definition"""

    class Meta:
        verbose_name_plural = "Amenities"


class Facility(AbstractItem):

    """Facility Model Definition"""

    class Meta:
        verbose_name_plural = "Facilities"


class HouseRule(AbstractItem):

    """HouseRule Model Definition"""

    class Meta:
        verbose_name = "House Rule"


class Room(core_models.TimeStampedModel):

    """Room Model Definition"""

    name = models.CharField(max_length=140)
    description = models.TextField()
    country = CountryField()
    city = models.CharField(max_length=80)
    price = models.IntegerField()
    address = models.CharField(max_length=140)
    guests = models.IntegerField()
    beds = models.IntegerField()
    bedrooms = models.IntegerField()
    baths = models.IntegerField()
    check_in = models.TimeField()
    check_out = models.TimeField()
    instant_book = models.BooleanField(default=False)
    host = models.ForeignKey(
        "users.User", on_delete=models.CASCADE, related_name="rooms"
    )
    room_type = models.ForeignKey(
        "RoomType", on_delete=models.SET_NULL, null=True, related_name="rooms"
    )
    amenities = models.ManyToManyField("Amenity", blank=True, related_name="rooms")
    facilities = models.ManyToManyField("Facility", blank=True, related_name="rooms")
    house_rules = models.ManyToManyField("HouseRule", blank=True, related_name="rooms")

    def __str__(self) -> str:
        return self.name

    def save(self, *args, **kwargs):
        self.city = str.capitalize(self.city)
        super().save(*args, **kwargs)

    def total_rating(self):
        all_reviews = self.reviews.all()
        all_ratings = 0
        for review in all_reviews:
            all_ratings += review.rating_average()
        if all_ratings:
            return round(all_ratings / len(all_reviews), 2)
        else:
            return 0

    def get_absolute_url(self):
        return reverse("rooms:detail", kwargs={"pk": self.pk})

    def first_photo(self):
        try:
            (photo,) = self.photos.all()[:1]
            return photo.file.url
        except ValueError:
            return None

    def get_next_four_photos(self):
        photos = self.photos.all()[1:5]
        return photos

    def get_calendars(self):
        this_month = timezone.now()
        next_month = this_month + relativedelta(months=1)
        this_cal = Calendar(self, this_month.year, this_month.month)
        next_cal = Calendar(self, next_month.year, next_month.month)
        return (this_cal, next_cal)


class Photo(core_models.TimeStampedModel):

    """Photo Model Definition"""

    caption = models.CharField(max_length=80)
    file = models.ImageField(upload_to="room_photos")
    room = models.ForeignKey("Room", on_delete=models.CASCADE, related_name="photos")

    def __str__(self) -> str:
        return self.caption

rooms/forms.py
from pyexpat import model
from typing_extensions import Required
from django import forms
from django_countries.fields import CountryField

from rooms.admin import RoomAdmin
from . import models


class SearchForm(forms.Form):

    city = forms.CharField(initial="Anywhere")
    country = CountryField(default="KR").formfield()
    room_type = forms.ModelChoiceField(
        empty_label="Any Kind", queryset=models.RoomType.objects.all(), required=False
    )
    price = forms.IntegerField(required=False)
    guests = forms.IntegerField(required=False)
    bedrooms = forms.IntegerField(required=False)
    beds = forms.IntegerField(required=False)
    baths = forms.IntegerField(required=False)
    instant_book = forms.BooleanField(required=False)
    is_superhost = forms.BooleanField(required=False)
    amenities = forms.ModelMultipleChoiceField(
        queryset=models.Amenity.objects.all(),
        widget=forms.CheckboxSelectMultiple,
        required=False,
    )
    facilities = forms.ModelMultipleChoiceField(
        queryset=models.Facility.objects.all(),
        widget=forms.CheckboxSelectMultiple,
        required=False,
    )
    house_rules = forms.ModelMultipleChoiceField(
        queryset=models.HouseRule.objects.all(),
        widget=forms.CheckboxSelectMultiple,
        required=False,
    )


class CreateForm(forms.ModelForm):
    class Meta:
        model = models.Room
        fields = [
            "name",
            "description",
            "country",
            "city",
            "price",
            "address",
            "guests",
            "beds",
            "bedrooms",
            "baths",
            "check_in",
            "check_out",
            "instant_book",
            "room_type",
            "amenities",
            "facilities",
            "house_rules",
        ]

    def save(self, commit=False):
        room = super().save(commit)
        return room


class PhotoForm(forms.ModelForm):
    class Meta:
        model = models.Photo
        fields = [
            "file",
            "caption",
        ]

    def save(self, pk, commit=False):
        photo = super().save(commit)
        room = models.Room.objects.get(pk=pk)
        photo.room = room
        photo.save()

rooms/views.py
from audioop import minmax
from email import message
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.contrib.messages.views import SuccessMessageMixin
from django.core.paginator import Paginator
from django.http import Http404
from django.shortcuts import render, redirect
from django.views.generic import ListView, DetailView, View, UpdateView, FormView
from django.urls import reverse
from . import models, forms
from users import mixins


class HomeView(ListView):

    """HomeView Definition"""

    model = models.Room
    paginate_by = 12
    paginate_orphans = 5
    ordering = "-created_at"
    context_object_name = "rooms"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        return context


class RoomDetailView(DetailView):

    """RoomDetailView Denifition"""

    model = models.Room


class SearchView(View):
    def get(self, request):

        country = request.GET.get("country")

        if country:

            form = forms.SearchForm(request.GET)

            if form.is_valid():

                city = form.cleaned_data.get("city")
                country = form.cleaned_data.get("country")
                room_type = form.cleaned_data.get("room_type")
                price = form.cleaned_data.get("price")
                guests = form.cleaned_data.get("guests")
                bedrooms = form.cleaned_data.get("bedrooms")
                beds = form.cleaned_data.get("beds")
                baths = form.cleaned_data.get("baths")
                instant_book = form.cleaned_data.get("instant_book")
                is_superhost = form.cleaned_data.get("is_superhost")
                amenities = form.cleaned_data.get("amenities")
                facilities = form.cleaned_data.get("facilities")
                house_rules = form.cleaned_data.get("house_rules")

                filter_args = {}

                if city != "Anywhere":
                    filter_args["city__startswith"] = city

                filter_args["country"] = country

                if room_type is not None:
                    filter_args["room_type__pk"] = room_type

                if price is not None:
                    filter_args["price__lte"] = price

                if guests is not None:
                    filter_args["guests__gte"] = guests

                if bedrooms is not None:
                    filter_args["bedrooms__gte"] = bedrooms

                if beds is not None:
                    filter_args["beds__gte"] = beds

                if baths is not None:
                    filter_args["baths__gte"] = baths

                if instant_book is True:
                    filter_args["instant_book"] = True

                if is_superhost is True:
                    filter_args["host__superhost"] = True

                for amenity in amenities:
                    filter_args["amenities"] = amenity

                for facility in facilities:
                    filter_args["facilities"] = facility

                for rule in house_rules:
                    filter_args["house_rules"] = rule

                qs = models.Room.objects.filter(**filter_args).order_by("-created_at")

                paginator = Paginator(qs, 10, orphans=5)

                rooms = paginator.get_page(1)

                return render(
                    request,
                    "rooms/search.html",
                    {"form": form, "rooms": rooms},
                )
        else:

            form = forms.SearchForm()

        return render(request, "rooms/search.html", {"form": form})


class CreateRoomView(mixins.LoggedInOnlyView, FormView):

    template_name = "rooms/room_create.html"
    form_class = forms.CreateForm

    def get(self, request, *args, **kwargs):
        print("get!!")
        if "is_hosting" in self.request.session:
            return super().get(request, *args, **kwargs)
        else:
            raise Http404()

    def form_valid(self, form):
        room = form.save()
        room.host = self.request.user
        room.save()
        form.save_m2m()
        messages.success(self.request, "Room created!!")
        return redirect(reverse("rooms:detail", kwargs={"pk": room.pk}))


class EditRoomView(mixins.LoggedInOnlyView, UpdateView):

    model = models.Room
    template_name = "rooms/room_edit.html"
    fields = [
        "name",
        "description",
        "country",
        "city",
        "price",
        "address",
        "guests",
        "beds",
        "bedrooms",
        "baths",
        "check_in",
        "check_out",
        "instant_book",
        "room_type",
        "amenities",
        "facilities",
        "house_rules",
    ]

    def get_object(self, queryset=None):
        room = super().get_object(queryset=queryset)
        if room.host.pk != self.request.user.pk:
            raise Http404()
        return room


class RoomPhotosView(mixins.LoggedInOnlyView, DetailView):

    model = models.Room
    template_name = "rooms/room_photos.html"

    def get_object(self, queryset=None):
        room = super().get_object(queryset=queryset)
        if room.host.pk != self.request.user.pk:
            raise Http404()
        return room

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        form = forms.PhotoForm
        context["photo_form"] = form
        return context


@login_required
def delete_photo(request, room_pk, photo_pk):
    user = request.user
    try:
        room = models.Room.objects.get(pk=room_pk)
        if room.host.pk != user.pk:
            messages.error(request, "Can't delete that photo")
        else:
            try:
                photo = models.Photo.objects.get(pk=photo_pk, room__pk=room_pk)
                photo.delete()
                messages.success(request, "Photo deleted!!")
            except models.Photo.DoesNotExist:
                messages.error(request, "Can't delete that photo")
        return redirect(reverse("rooms:photos", kwargs={"pk": room_pk}))
    except models.Room.DoesNotExist:
        return redirect(reverse("core:home"))


class EditPhotoView(mixins.LoggedInOnlyView, SuccessMessageMixin, UpdateView):

    model = models.Photo
    template_name = "rooms/photo_edit.html"
    pk_url_kwarg = "photo_pk"
    fields = [
        "caption",
    ]
    success_message = "File Updated!!"

    def get_object(self, queryset=None):
        room_pk = self.kwargs.get("room_pk")
        room = models.Room.objects.get(pk=room_pk)
        if room.host.pk != self.request.user.pk:
            raise Http404()
        photo = super().get_object(queryset=queryset)
        return photo

    def get_success_url(self):
        room_pk = self.kwargs.get("room_pk")
        return reverse("rooms:photos", kwargs={"pk": room_pk})


class CreatePhotoView(mixins.LoggedInOnlyView, FormView):

    model = models.Photo
    fields = [
        "file",
        "caption",
    ]
    form_class = forms.PhotoForm
    template_name = "rooms/room_photos.html"

    def form_valid(self, form):
        pk = self.kwargs.get("pk")
        print(pk)
        form.save(pk)
        messages.success(self.request, "Photo uploaded!!")
        return redirect(reverse("rooms:photos", kwargs={"pk": pk}))

templates/rooms/photo_edit.html
{% extends 'base.html' %}

{% block page_title %}
    Edit Photo
{% endblock page_title %}

{% block search-bar %}{% endblock search-bar %}

{% block content %}

    <div class="wrap-user">

        {% include 'mixins/auth/auth_form.html' with form=form cta="Update photo" %}

        <div class="mt-4 text-sm w-full text-center">
            <span class="mr-2"><a href="{% url 'rooms:photos' photo.room.pk %}" class="text-teal-600 font-bold">Back to photos</a>
        </div>
    </div>

{% endblock content %}

templates/rooms/room_create.html
{% extends 'base.html' %}

{% block page_title %}
    Create Room
{% endblock page_title %}

{% block content %}

    <div class="wrap-user">

        {% include 'mixins/auth/auth_form.html' with form=form cta="Create room" %}

    </div>

{% endblock content %}

templates/rooms/room_detail.html
{% extends 'base.html' %} 
{% load i18n on_favs %}

{% block page_title %}{{room.name}}{% endblock page_title %} 

{% block content %}

<div class="container max-w-7xl mx-auto pt-8">
    <div>
        <div class="flex items-center">
            <h2 class="text-3xl font-bold">{{room.name}}</h2>
            <div class="ml-4">
            {% on_favs room as on_favs_boolean %}
            {% if on_favs_boolean %}
                <a href="{% url 'lists:toggle' room.pk %}?action=remove" class="c-btn-link btn--small">Remove Favorite List</a>
            {% else %}
                <a href="{% url 'lists:toggle' room.pk %}?action=add" class="c-btn-link btn--small bg-teal-600">Add Favorite List</a>
            {% endif %}
            </div>
        </div>
        <ul class="flex gap-4 mt-2">
            <li><i class="fas fa-star fa-sm mr-1"></i><span class="sr-only">total rating:</span>{{room.total_rating}}</li>
            <li><i class="far fa-eye fa-sm mr-1"></i><span class="sr-only">view counts:</span>{{room.reviews.count}}</li>
            <li><i class="fas fa-flag fa-sm mr-1"></i><span class="sr-only">country:</span>{{room.country.name}}</li>
            <li><i class="fas fa-building fa-sm mr-1"></i><span class="sr-only">city:</span>{{room.city}}</li>
            {% if room.host.is_superhost %}
            <li class="text-sm border border-gray-500 rounded font-bold px-2">SUPERHOST</li>
            {% endif %}
            <li>
        </ul>
    </div>

    <div class="h-50vh w-full flex mt-8">
        <div class="h-full w-1/2 bg-cover border-4 border-white rounded-tl-2xl rounded-bl-2xl" style="background-image:url({{room.first_photo}})"></div>
        <div class="h-full w-1/2 flex flex-wrap">
        {% for photo in room.get_next_four_photos %}
            <div class="h-1/2 w-1/2 bg-cover border-4 border-white {% if forloop.counter == 2 %}rounded-tr-2xl{% elif forloop.counter == 4 %}rounded-br-2xl{% endif %} " style="background-image:url({{photo.file.url}})"></div>
        {% endfor %}
        </div>
    </div>

    <div class="mt-8 w-full flex justify-between">
        <div class="w-2/3">
            <div class="flex justify-between items-center pb-4 border-b mb-8">
                <div>
                    <h3 class="text-2xl">
                        {{room.room_type}} information hosted by <a class="font-bold text-teal-700" href="{{room.host.get_absolute_url}}">{{room.host.first_name}}</a>
                    </h3>
                    <ul class="flex gap-x-4">
                        <li>{% trans "Max Guests" %}: {{room.guests}}</li>
                        <li>{% trans "Bed rooms" %}: {{room.bedrooms}}</li>
                        <li>{% trans "Beds" %}: {{room.beds}}</li>
                        <li>{% trans "Baths" %}: {{room.baths}}</li>
                    </ul>
                </div>
                <div>
                    {% include 'mixins/user_avatar.html' with user=room.host %}
                </div>
            </div>
            <div class="border-section">
                <p>{{room.description}}</p>
            </div>
            <div class="border-section">
                <h4>{% trans "Amenities" %}</h4>
                <ul class="w-full flex flex-wrap list-disc list-inside">
                {% for a in room.amenities.all %}
                    <li class="w-1/2">{{a}}</li>
                {% endfor %}
                </ul>
            </div>
            <div class="border-section">
                <h4>{% trans "Facilities" %}</h4>
                <ul class="w-full flex flex-wrap list-disc list-inside">
                {% for f in room.facilities.all %}
                    <li class="w-1/2">{{f}}</li>
                {% endfor %}
                </ul>
            </div>
            <div class="border-section">
                <h4>{% trans "House Rules" %}</h4>
                <ul class="w-full flex flex-wrap list-disc list-inside">
                {% for h in room.house_rules.all %}
                    <li class="w-1/2">{{h}}</li>
                {% endfor %}
                </ul>
            </div>
            <div class="border-section border-none">
                <div class="flex items-center gap-8">
                    <h4 class="text-2xl mb-0">{% trans "Reviews" %}</h4>
                    <ul class="flex gap-4 items-center">
                        <li>
                            <i class="fas fa-star fa-sm text-teal-700"></i>
                            <span class="sr-only">total rating:</span>
                            <span class="font-bold text-xl">{{room.total_rating}}</span>
                        </li>
                        <li><span class="font-bold text-xl">{{room.reviews.count}}</span> review{{room.reviews.count|pluralize}}</li>
                    </ul>
                </div>
                <div class="flex flex-col">
                    {% for review in room.reviews.all %}
                    <div class="py-8 border-b">
                        <div class="flex items-center mb-4">
                            <div>
                                {% include 'mixins/user_avatar.html' with user=review.user w_and_h="w-14 h-14" text="text-2xl" %}
                            </div>
                            <div class="flex flex-col ml-4">
                                <span class="font-bold text-lg">{{review.user.first_name}}</span>
                                <span class="text-gray-700">{{review.created_at|date:"F Y"}}</span>
                            </div>
                        </div>
                        <p>{{review.review}}</p>
                    </div>
                    {% endfor %}
                </div>
            </div>
        </div>
        <div class="w-1/3 ml-12">
        {% if room.host == user %}
            <a href="{% url 'rooms:edit' room.pk %}" class="c-btn-link block">Edit Room</a>
        {% else %}
            {% if not request.session.is_hosting %}
                {% for calendar in room.get_calendars %}
                <div class="w-full">
                    <h4 class="text-center">{{calendar.get_month}}/{{calendar.year}}</h4>
                    <table class="calendar">
                        <thead>
                            <tr>
                            {% for day in calendar.day_names %}
                                <th scope="col">{{day}}</th>
                            {% endfor %}
                            </tr>
                        </thead>
                        <tbody>
                            {% for week in calendar.get_days %}
                            <tr>
                                {% for cal_date in week %}
                                {% include 'mixins/cal_day.html' with cal_date=cal_date %}
                                {% endfor %}
                            </tr>
                            {% endfor %}
                    
                        </tbody>
                    </table>
                </div>
                {% endfor %}
            {% endif %}
        {% endif %}
        </div>
    </div>
</div>

{% endblock content %}

templates/rooms/room_edit.html
{% extends 'base.html' %}

{% block page_title %}
    Update Room : {{room.name}}
{% endblock page_title %}

{% block content %}

    <div class="wrap-user">

        {% include 'mixins/auth/auth_form.html' with form=form cta="Update room" %}

        <div class="mt-4 text-sm w-full text-center">
            <span class="mr-2"><a href="{% url 'rooms:photos' room.pk %}" class="text-teal-600 font-bold">Edit Photos</a>
        </div>
    </div>

{% endblock content %}

templates/rooms/room_list.html
{% extends 'base.html' %} 

{% block page_title %}Home{% endblock page_title %} 

{% block content %}

    <div class="container rounded-2xl bg-gray-800 h-50vh my-12 bg-cover bg-center" style="background-image:url(https://images.unsplash.com/photo-1546874177-9e664107314e?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=2069&q=80)"></div>

    <div class="flex flex-wrap mb-4">
    {% for room in rooms %}
        {% include 'partials/room_card.html' %}
    {% endfor %}
    </div>

    <!-- https://docs.djangoproject.com/en/4.1/ref/templates/builtins/ 참조 -->
    <div class="flex items-center justify-center text-lg">
        {% if page_obj.has_previous %}
            <a href="?page={{page_obj.previous_page_number}}" aria-label="Previous page" class="text-teal-600"><i class="fas fa-arrow-left fa-lg"></i></a>
        {% endif %} 
        
        <span class="mx-2">Page {{page_obj.number}} of {{page_obj.paginator.num_pages}}</span>
        
        {% if page_obj.has_next %}
            <a href="?page={{page_obj.next_page_number}}" aria-label="Next page" class="text-teal-600"><i class="fas fa-arrow-right fa-lg"></i></a>
        {% endif %}
    </div>

{% endblock content %}

templates/rooms/room_photos.html
{% extends 'base.html' %}

{% block page_title %}
    {{room.name}}'s Photos
{% endblock page_title %}

{% block search-bar %}{% endblock search-bar %}

{% block content %}

    <div class="mt-12 text-right mb-8">
        <a href="{% url 'rooms:detail' room.pk %}" class="c-btn-link px-8">Go to the room</a>
    </div>

    <div class="text-right mb-8">
        <form method="post" action="{% url 'rooms:add-photo' room.pk %}" enctype="multipart/form-data" class="w-full">
            <fieldset class="w-full flex items-end gap-4 p-2 border text-left">
                <legend class="text-xl font-bold">Photo Upload</legend>
                {% csrf_token %}
                <div class="w-3/12">
                    {{photo_form.file.label_tag}}{{photo_form.file.errors}}
                    {{photo_form.file}}
                </div>
                <div class="w-7/12">
                    {{photo_form.caption.label_tag}}{{photo_form.file.errors}}
                    {{photo_form.caption}}
                </div>
                <div class="w-2/12">
                    <button type="submit" class="c-btn-full px-12 mb-0" href="{% url 'rooms:add-photo' room.pk %}">Upload Photo</button>
                </div>
            </fieldset>
        </form>
    </div>

    <div class="grid lg:grid-cols-2 grid-cols-1 gap-4">

    {% for photo in room.photos.all %}
        <div class="p-2 border border-gray-300 flex">
            <img class="w-52" src="{{photo.file.url}}" alt="" />
            <div class="w-full flex flex-col justify-between">
                <div>
                    <span class="ml-3 text-xl">{{photo.caption}}</span>
                </div>
                <div class="p-4 flex">
                    <a class="c-btn-link block mr-2 bg-teal-700" href="{% url 'rooms:photo-edit' room.pk photo.pk %}">Edit Photo</a>
                    <a class="c-btn-link block ml-2 bg-red-700" href="{% url 'rooms:photo-delete' room.pk photo.pk %}">Delete Photo</a>
                </div>
            </div>
        </div>
    {% endfor %}

    </div>

{% endblock content %}

templates/rooms/search.html
{% extends 'base.html' %}

{% block page_title %}
    Search
{% endblock page_title %}

{% block search-bar %}{% endblock search-bar %}

{% block content %}

    <h2>Search!</h2>

    <form method="get" action="{% url 'rooms:search' %}">
        {{form.as_p}}
        <button>Search</button>
    </form>

    <h3>Search Results</h3>

    <ul>
    {% for room in rooms %}
        <li>{{room.name}}</li>
    {% endfor %}
    </ul>

{% endblock content %}