config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("", include("core.urls", namespace="core")),
    path("rooms/", include("rooms.urls", namespace="rooms")),
    path("users/", include("users.urls", namespace="users")),
    path("reservations/", include("reservations.urls", namespace="reservations")),
    path("reviews/", include("reviews.urls", namespace="reviews")),
    path("lists/", include("lists.urls", namespace="lists")),
    path("conversations/", include("conversations.urls", namespace="conversations")),
    path("admin/", admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

conversations/urls.py
from django.urls import path
from . import views

app_name = "conversations"

urlpatterns = [
    path("go/<int:a_pk>/<int:b_pk>/", views.go_conversation, name="go"),
    path("<int:pk>/", views.ConversationDetailView.as_view(), name="detail"),
]

core/urls.py
from django.urls import path
from rooms import views as room_views

app_name = "core"

urlpatterns = [
    path("", room_views.HomeView.as_view(), name="home"),
]

reservations/urls.py
from django.urls import path
from . import views

app_name = "reservations"

urlpatterns = [
    path(
        "create/<int:room>/<int:year>-<int:month>-<int:day>/",
        views.create,
        name="create",
    ),
    path("<int:pk>/", views.DetailView.as_view(), name="detail"),
    path("<int:pk>/<str:verb>/", views.edit_reservation, name="edit"),
]

reservations/models.py
from django.db import models
from django.utils import timezone
from core import models as core_models


class Reservation(core_models.TimeStampedModel):

    """Reservation Model Definition"""

    STATUS_PENDING = "pending"
    STATUS_CONFIRMED = "confirmed"
    STATUS_CANCELED = "canceled"

    STATUS_CHOICES = (
        (STATUS_PENDING, "Pending"),
        (STATUS_CONFIRMED, "Confirmed"),
        (STATUS_CANCELED, "Canceled"),
    )

    status = models.CharField(
        max_length=12, choices=STATUS_CHOICES, default=STATUS_PENDING
    )
    check_in = models.DateField()
    check_out = models.DateField()
    guest = models.ForeignKey(
        "users.User", on_delete=models.CASCADE, related_name="reservations"
    )
    room = models.ForeignKey(
        "rooms.Room", on_delete=models.CASCADE, related_name="reservations"
    )

    def __str__(self) -> str:
        return f"{self.room} - {self.check_in}"

    def in_progress(self):
        now = timezone.now().date()
        return now >= self.check_in and now <= self.check_out

    in_progress.boolean = True

    def is_finished(self):
        now = timezone.now().date()
        return now > self.check_out

    is_finished.boolean = True

reservations/views.py
import datetime
from django.contrib import messages
from django.db.models.query import Q
from django.http import Http404
from django.shortcuts import render, redirect
from django.urls import reverse
from django.views.generic import View
from . import models
from reviews import forms as review_forms
from rooms import models as room_models


class CreateError(Exception):
    pass


def create(request, room, year, month, day):
    try:
        date_obj = datetime.datetime(year, month, day)
        print(date_obj)
        room = room_models.Room.objects.get(pk=room)
        print(room)
        room.reservations.get(
            Q(check_in__lte=date_obj, check_out__gte=date_obj) & ~Q(status="canceled")
        )
        raise CreateError()
    except (room_models.Room.DoesNotExist, CreateError):
        messages.error(request, "Can't Reserve That Room")
        return redirect(reverse("core:home"))
    except models.Reservation.DoesNotExist:
        reservation = models.Reservation.objects.create(
            check_in=date_obj,
            check_out=date_obj + datetime.timedelta(days=1),
            guest=request.user,
            room=room,
        )
        return redirect(reverse("reservations:detail", kwargs={"pk": reservation.pk}))


class DetailView(View):
    def get(self, request, pk):
        reservation = models.Reservation.objects.get_or_none(pk=pk)
        print(reservation)
        if not reservation:
            print("404")
            raise Http404()

        print(reservation.guest, request.user)
        if reservation.guest != request.user and reservation.room.host != request.user:
            raise Http404()
        form = review_forms.CreateReviewForm()
        return render(
            request,
            "reservations/detail.html",
            {"reservation": reservation, "review_form": form},
        )


def edit_reservation(request, pk, verb):
    reservation = models.Reservation.objects.get_or_none(pk=pk)
    if not reservation or (
        reservation.guest != request.user and reservation.room.host != request.user
    ):
        raise Http404()
    if verb == "confirm":
        reservation.status = models.Reservation.STATUS_CONFIRMED
    elif verb == "cancel":
        reservation.status = models.Reservation.STATUS_CANCELED

    reservation.save()
    messages.success(request, "Reservation UPdated!!")
    return redirect(reverse("reservations:detail", kwargs={"pk": reservation.pk}))

templates/reservations/detail.html
{% extends 'base.html' %}

{% block page_title %}
    Reservation {{reservation.check_in}}
{% endblock page_title %}

{% block content %}

    <div class="container max-w-7xl mx-auto pt-8">
    
        <div class="mt-8 w-full flex justify-between">
            <div class="w-2/3">
                <div class="py-4 border-b">
                    <h3 class="text-2xl">
                        {{reservation.room.name}}
                    </h3>
                </div>
                <div class="py-4 border-b">
                    <span>{{reservation.check_in}} - {{reservation.check_out}}</span>
                    <span class="ml-4 {% if reservation.status == "pending" %}text-yellow-600{% elif reservation.status == "canceled" %}text-red-600{% else %}text-teal-600{% endif %}"> {{reservation.get_status_display}}</span>
                </div>
                <div class="py-4 border-b flex">
                    <div class="flex flex-col items-center">
                        {% include 'mixins/user_avatar.html' with user=reservation.room.host %}
                        <span class="mt-2">{{reservation.room.host.username}}</span>
                    </div>
                    <div class="ml-6">
                        <div class="font-bold mb-1">Contact your Airbnb Host</div>
                        <a href="{% url 'conversations:go' reservation.room.host.pk reservation.guest.pk %}" class="text-teal-600">Send a Message</a>
                    </div>
                </div>
                <div class="border-section pt-8">
                    {% if reservation.status != 'canceled' %}
                        {% if reservation.status == 'confirmed' and reservation.is_finished and reservation.guest == user %}
                            <h4>Write your review</h4>
                            <form action="{% url 'reviews:create' reservation.room.pk %}" method="POST">
                                {% csrf_token %}
                                {{review_form.as_div}}
                                <button type="submit" class="c-btn-full mt-4">Submit Review</button>
                            </form>
                        {% else %}
                            {% if reservation.status == "pending" %}
                            <a href="{% url 'reservations:edit' reservation.pk "cancel" %}" class="c-btn-link px-4">Cancel Reservation</a>
                                {% if reservation.room.host == user %}
                                <a href="{% url 'reservations:edit' reservation.pk "confirm" %}" class="c-btn-link px-4">Confirm Reservation</a>
                                {% endif %}
                            {% endif %}
                        {% endif %}
                    {% endif %}
                </div>
                <div class="mt-12 text-right mb-8">
                    <a href="{% url 'rooms:detail' reservation.room.pk %}" class="c-btn-link px-8">Go to the room</a>
                </div>                
            </div>
            <div class="w-1/3 ml-12">
                <div class="w-full h-full bg-cover bg-center rounded-r-xl" style="background-image:url('{{reservation.room.first_photo}}');">
                </div>
            </div>
        </div>
    </div>

{% endblock content %}